import { AgentSkill } from "../../harness/index.ts";

export const CreateStudyArtifactsSkill = AgentSkill.make({
  name: "create-study-artifacts",
  description: "Create, list, submit or grade study artifacts (notes, quizzes, tests). Only when the user asks for one of those actions.",
  content: [
    "# Create study artifacts",
    "",
    "Use this skill when the user asks you to create study notes, quizzes, tests, or practice submissions.",
    "",
    "Artifacts are persisted study objects:",
    "- `note`: title plus markdown content. Notes are not submitted or graded.",
    "- `quiz`: title plus auto-gradable multiple-choice / true-false questions.",
    "- `test`: title plus questions. Tests may include multiple-choice, true-false, and short-answer questions.",
    "",
    "Available CLI commands:",
    "- `artifacts list [note|quiz|test]`: list saved artifacts.",
    "- `artifacts show <artifactId>`: show an artifact JSON.",
    "- `artifacts create '<json>'`: create a note, quiz, or test from CreateArtifactInput JSON. Always wrap JSON in single quotes.",
    "- `artifacts submit '<json>'`: submit answers for a quiz or test from SubmitAttemptInput JSON. Always wrap JSON in single quotes.",
    "- `artifacts attempts [artifactId]`: list attempts.",
    "- `artifacts grade <attemptId>`: grade and persist a submitted attempt.",
    "",
    "CreateArtifactInput examples:",
    "- `artifacts create '{\"kind\":\"note\",\"title\":\"Derivatives summary\",\"markdown\":\"# Derivatives\\n...\"}'`",
    "- `artifacts create '{\"kind\":\"quiz\",\"title\":\"Basics quiz\",\"questions\":[{\"type\":\"true-false\",\"id\":\"q1\",\"prompt\":\"2+2=4\",\"correctAnswer\":true,\"explanation\":\"Basic arithmetic.\"}]}'`",
    "- `artifacts create '{\"kind\":\"quiz\",\"title\":\"Concept quiz\",\"source\":{\"materialId\":\"algebra-notes\",\"pages\":[2]},\"questions\":[{\"type\":\"multiple-choice\",\"id\":\"q1\",\"prompt\":\"Which option is qualitative?\",\"options\":[{\"id\":\"qualitative\",\"text\":\"Qualitative\"},{\"id\":\"quantitative\",\"text\":\"Quantitative\"}],\"correctOptionId\":\"qualitative\",\"explanation\":\"Qualitative data describes qualities.\",\"sourcePage\":2}]}'`",
    "",
    "Multiple-choice question rules:",
    "- `options` must be objects, not strings: `{\"id\":\"a\",\"text\":\"Option text\"}`.",
    "- `correctOptionId` must exactly match one option `id`.",
    "",
    "Citing an uploaded material:",
    "- When an artifact is created from an uploaded PDF (via `materials text` or `materials view`),",
    "  always set `source: { materialId, pages }` on the artifact with the material id and the",
    "  page(s) you used.",
    "- Always set `sourcePage` on each question created from that material, with the exact page",
    "  the question came from. If you are not sure which page a question came from, omit",
    "  `sourcePage` for that question rather than guessing.",
    "- Do not set `source` or `sourcePage` for artifacts written from general knowledge, not from",
    "  an uploaded PDF.",
    "",
    "SubmitAttemptInput example:",
    "- `artifacts submit '{\"artifactKind\":\"quiz\",\"artifactId\":\"<id>\",\"answers\":[{\"questionType\":\"true-false\",\"questionId\":\"q1\",\"answer\":true}]}'`",
    "",
    "Workflow:",
    "1. If the user asks for an artifact about a specific uploaded PDF, render the relevant pages first. If they ask for one about a general topic, write it from your own knowledge.",
    "2. Create a compact artifact that directly matches the user's request.",
    "3. Use stable question ids like `q1`, `q2`, `q3`.",
    "4. For quizzes, prefer true-false and multiple-choice because grading is deterministic.",
    "5. When a user submits answers, save the attempt and then grade it."
  ].join("\n")
});
